server:
  port: 30880
  
spring:
  dubbo:
    application:
      name: add-service
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20880
    scan: io.springboard.calculate
